# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nTask.proto\"(\n\x0bTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"\x1d\n\x0bListRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\"K\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\x19\n\x08resolved\x18\x04 \x01(\x0e\x32\x07.Status\"#\n\x0cTaskResponse\x12\x13\n\x04Task\x18\x01 \x01(\x0b\x32\x05.Task\"\'\n\x10TaskListResponse\x12\x13\n\x04Task\x18\x01 \x03(\x0b\x32\x05.Task*&\n\x06Status\x12\x0c\n\x08RESOLVED\x10\x00\x12\x0e\n\nUNRESOLVED\x10\x01\x32\x90\x01\n\x0bTaskService\x12)\n\ncreateTask\x12\x0c.TaskRequest\x1a\r.TaskResponse\x12+\n\x08getTasks\x12\x0c.ListRequest\x1a\x11.TaskListResponse\x12)\n\nmodifyTask\x12\x0c.TaskRequest\x1a\r.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=242
  _globals['_STATUS']._serialized_end=280
  _globals['_TASKREQUEST']._serialized_start=14
  _globals['_TASKREQUEST']._serialized_end=54
  _globals['_LISTREQUEST']._serialized_start=56
  _globals['_LISTREQUEST']._serialized_end=85
  _globals['_TASK']._serialized_start=87
  _globals['_TASK']._serialized_end=162
  _globals['_TASKRESPONSE']._serialized_start=164
  _globals['_TASKRESPONSE']._serialized_end=199
  _globals['_TASKLISTRESPONSE']._serialized_start=201
  _globals['_TASKLISTRESPONSE']._serialized_end=240
  _globals['_TASKSERVICE']._serialized_start=283
  _globals['_TASKSERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
