# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: taskAdmin
      POSTGRES_PASSWORD: mdppostgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  envoy:
    image: envoyproxy/envoy:v1.21.0
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  frontend:
    container_name: frontend
    image: node:18-alpine
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    working_dir: /frontend
    command: [ "npm", "start" ]
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
    command: [ "bash", "docker-entry-point.sh" ]
    ports:
      - "50051:50051"
    depends_on:
      - db
