# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: taskAdmin
      POSTGRES_PASSWORD: mdppostgres
    ports:
      - 5432:5432
