# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TaskRefs_pb2 as TaskRefs__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class TaskRefsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createTaskRef = channel.unary_unary(
                '/TaskRefsService/createTaskRef',
                request_serializer=TaskRefs__pb2.CreateTaskRefRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.getTaskRef = channel.unary_unary(
                '/TaskRefsService/getTaskRef',
                request_serializer=TaskRefs__pb2.GetTaskRefRequest.SerializeToString,
                response_deserializer=TaskRefs__pb2.GetTaskRefResponse.FromString,
                )
        self.getAllTaskRefs = channel.unary_unary(
                '/TaskRefsService/getAllTaskRefs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=TaskRefs__pb2.GetAllTaskRefsResponse.FromString,
                )
        self.updateTaskRef = channel.unary_unary(
                '/TaskRefsService/updateTaskRef',
                request_serializer=TaskRefs__pb2.UpdateTaskRefRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TaskRefsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createTaskRef(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTaskRef(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllTaskRefs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTaskRef(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskRefsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createTaskRef': grpc.unary_unary_rpc_method_handler(
                    servicer.createTaskRef,
                    request_deserializer=TaskRefs__pb2.CreateTaskRefRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getTaskRef': grpc.unary_unary_rpc_method_handler(
                    servicer.getTaskRef,
                    request_deserializer=TaskRefs__pb2.GetTaskRefRequest.FromString,
                    response_serializer=TaskRefs__pb2.GetTaskRefResponse.SerializeToString,
            ),
            'getAllTaskRefs': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllTaskRefs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=TaskRefs__pb2.GetAllTaskRefsResponse.SerializeToString,
            ),
            'updateTaskRef': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTaskRef,
                    request_deserializer=TaskRefs__pb2.UpdateTaskRefRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TaskRefsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskRefsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createTaskRef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskRefsService/createTaskRef',
            TaskRefs__pb2.CreateTaskRefRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getTaskRef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskRefsService/getTaskRef',
            TaskRefs__pb2.GetTaskRefRequest.SerializeToString,
            TaskRefs__pb2.GetTaskRefResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllTaskRefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskRefsService/getAllTaskRefs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            TaskRefs__pb2.GetAllTaskRefsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateTaskRef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskRefsService/updateTaskRef',
            TaskRefs__pb2.UpdateTaskRefRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
