# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskRefs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eTaskRefs.proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x14\x43reateTaskRefRequest\x12\x0e\n\x06idTask\x18\x01 \x01(\x05\"&\n\x11GetTaskRefRequest\x12\x11\n\tidTaskRef\x18\x01 \x01(\x05\"Y\n\x12GetTaskRefResponse\x12\x11\n\tidTaskRef\x18\x01 \x01(\x05\x12\x0e\n\x06idTask\x18\x02 \x01(\x05\x12\x0e\n\x06idList\x18\x03 \x01(\x05\x12\x10\n\x08selected\x18\x04 \x01(\x08\"m\n\x14UpdateTaskRefRequest\x12\x11\n\tidTaskRef\x18\x01 \x01(\x05\x12\x13\n\x06idList\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08selected\x18\x04 \x01(\x08H\x01\x88\x01\x01\x42\t\n\x07_idListB\x0b\n\t_selected\"?\n\x16GetAllTaskRefsResponse\x12%\n\x08taskRefs\x18\x01 \x03(\x0b\x32\x13.GetTaskRefResponse2\x8b\x02\n\x0fTaskRefsService\x12>\n\rcreateTaskRef\x12\x15.CreateTaskRefRequest\x1a\x16.google.protobuf.Empty\x12\x35\n\ngetTaskRef\x12\x12.GetTaskRefRequest\x1a\x13.GetTaskRefResponse\x12\x41\n\x0egetAllTaskRefs\x12\x16.google.protobuf.Empty\x1a\x17.GetAllTaskRefsResponse\x12>\n\rupdateTaskRef\x12\x15.UpdateTaskRefRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TaskRefs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATETASKREFREQUEST']._serialized_start=47
  _globals['_CREATETASKREFREQUEST']._serialized_end=85
  _globals['_GETTASKREFREQUEST']._serialized_start=87
  _globals['_GETTASKREFREQUEST']._serialized_end=125
  _globals['_GETTASKREFRESPONSE']._serialized_start=127
  _globals['_GETTASKREFRESPONSE']._serialized_end=216
  _globals['_UPDATETASKREFREQUEST']._serialized_start=218
  _globals['_UPDATETASKREFREQUEST']._serialized_end=327
  _globals['_GETALLTASKREFSRESPONSE']._serialized_start=329
  _globals['_GETALLTASKREFSRESPONSE']._serialized_end=392
  _globals['_TASKREFSSERVICE']._serialized_start=395
  _globals['_TASKREFSSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
