/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: Task.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as Task_pb from './Task_pb';


export class TaskServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorcreateTask = new grpcWeb.MethodDescriptor(
    '/TaskService/createTask',
    grpcWeb.MethodType.UNARY,
    Task_pb.TaskRequest,
    Task_pb.TaskResponse,
    (request: Task_pb.TaskRequest) => {
      return request.serializeBinary();
    },
    Task_pb.TaskResponse.deserializeBinary
  );

  createTask(
    request: Task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null): Promise<Task_pb.TaskResponse>;

  createTask(
    request: Task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Task_pb.TaskResponse) => void): grpcWeb.ClientReadableStream<Task_pb.TaskResponse>;

  createTask(
    request: Task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Task_pb.TaskResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TaskService/createTask',
        request,
        metadata || {},
        this.methodDescriptorcreateTask,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TaskService/createTask',
    request,
    metadata || {},
    this.methodDescriptorcreateTask);
  }

  methodDescriptorgetTasks = new grpcWeb.MethodDescriptor(
    '/TaskService/getTasks',
    grpcWeb.MethodType.UNARY,
    Task_pb.ListRequest,
    Task_pb.TaskListResponse,
    (request: Task_pb.ListRequest) => {
      return request.serializeBinary();
    },
    Task_pb.TaskListResponse.deserializeBinary
  );

  getTasks(
    request: Task_pb.ListRequest,
    metadata: grpcWeb.Metadata | null): Promise<Task_pb.TaskListResponse>;

  getTasks(
    request: Task_pb.ListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Task_pb.TaskListResponse) => void): grpcWeb.ClientReadableStream<Task_pb.TaskListResponse>;

  getTasks(
    request: Task_pb.ListRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Task_pb.TaskListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TaskService/getTasks',
        request,
        metadata || {},
        this.methodDescriptorgetTasks,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TaskService/getTasks',
    request,
    metadata || {},
    this.methodDescriptorgetTasks);
  }

  methodDescriptormodifyTask = new grpcWeb.MethodDescriptor(
    '/TaskService/modifyTask',
    grpcWeb.MethodType.UNARY,
    Task_pb.TaskRequest,
    Task_pb.TaskResponse,
    (request: Task_pb.TaskRequest) => {
      return request.serializeBinary();
    },
    Task_pb.TaskResponse.deserializeBinary
  );

  modifyTask(
    request: Task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null): Promise<Task_pb.TaskResponse>;

  modifyTask(
    request: Task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Task_pb.TaskResponse) => void): grpcWeb.ClientReadableStream<Task_pb.TaskResponse>;

  modifyTask(
    request: Task_pb.TaskRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Task_pb.TaskResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TaskService/modifyTask',
        request,
        metadata || {},
        this.methodDescriptormodifyTask,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TaskService/modifyTask',
    request,
    metadata || {},
    this.methodDescriptormodifyTask);
  }

}

