"""deleting date collumn

Revision ID: 17cefa339dfa
Revises: a29080706884
Create Date: 2023-10-02 14:23:57.799549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17cefa339dfa'
down_revision: Union[str, None] = 'a29080706884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'truc')
    op.drop_column('task', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('truc', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
