"""first database

Revision ID: 2306de167d25
Revises: 
Create Date: 2023-10-04 14:56:26.053744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2306de167d25"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("idTask", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("idTask"),
    )
    op.create_table(
        "task_refs",
        sa.Column("idTaskRef", sa.Integer(), nullable=False),
        sa.Column("idTask", sa.Integer(), nullable=False),
        sa.Column("idList", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("idTaskRef"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_refs")
    op.drop_table("task")
    # ### end Alembic commands ###
