"""removing 'selected' collumn in db

Revision ID: 74e8ca3b4813
Revises: e17b0588c984
Create Date: 2023-10-17 14:43:53.446768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e8ca3b4813'
down_revision: Union[str, None] = 'e17b0588c984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task', ['id_task'])
    op.drop_column('task_refs', 'selected')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_refs', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='unique')
    # ### end Alembic commands ###
