"""first db

Revision ID: e17b0588c984
Revises: 
Create Date: 2023-10-10 16:41:43.374305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17b0588c984'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id_task', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_task'),
    sa.UniqueConstraint('id_task')
    )
    op.create_table('task_refs',
    sa.Column('id_task_ref', sa.UUID(), nullable=False),
    sa.Column('id_task', sa.UUID(), nullable=False),
    sa.Column('id_list', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_task'], ['task.id_task'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_task_ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_refs')
    op.drop_table('task')
    # ### end Alembic commands ###
